version: '3.8'

services:
  db_backend_user:
    container_name: db_backend_user
    image: mongo:5.0.3
    restart: always
    env_file: .env
    ports:
      - 27017:27017
  backend_user:
    build: .
    container_name: backend_user
    ports:
      - 8080:3000
    env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db_backend_user
